# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RaidHamina
description: > # this means to ignore newlines until "baseurl:"
  RaidHamina ohjeet
baseurl: "/" # the subpath of your site, e.g. /blog
basedomain: "raidhamina.nocturnal.fi"
url: "https://raidhamina.nocturnal.fi" # the base hostname & protocol for your site
theme: default

# Build settings
markdown: kramdown
destination: /srv/www/ro/raidhamina
